-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 26, 2017 at 10:53 AM
-- Server version: 10.1.22-MariaDB
-- PHP Version: 7.0.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `php3_assignment`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `name`, `parent_id`, `created_at`, `updated_at`) VALUES
(1, 'xã hội', -1, NULL, NULL),
(2, 'giáo dục', -1, NULL, NULL),
(3, 'thể thao', -1, NULL, NULL),
(4, 'bóng đá', 3, NULL, NULL),
(5, 'đời sống', 1, NULL, NULL),
(6, 'chungnq update', 1, '2017-09-26 00:59:49', '2017-09-26 01:00:36');

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_resets_table', 1),
(3, '2017_09_16_082849_create_categories_table', 1),
(4, '2017_09_21_072206_create_posts_table', 1);

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

CREATE TABLE `password_resets` (
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` int(10) UNSIGNED NOT NULL,
  `title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `short_desc` text COLLATE utf8mb4_unicode_ci,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `cate_id` int(11) NOT NULL,
  `author` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `views` int(11) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `title`, `short_desc`, `content`, `cate_id`, `author`, `views`, `created_at`, `updated_at`) VALUES
(1, 'Alice could not Ada,\' she walked two reasons. First, however, it did it,) he added, to herself.', 'But if I\'m not the smallest notice of them hit her in such confusion that she never knew whether it was the same tone, exactly as if she were looking over their heads. She felt that there was the.', 'Mouse to tell them something more. \'You promised to tell me your history, you know,\' said Alice, \'and why it is you hate--C and D,\' she added in a whisper, half afraid that it would be offended again. \'Mine is a long and a sad tale!\' said the Mouse, turning to Alice, and sighing. \'It IS a long tail, certainly,\' said Alice, looking down with wonder at the Mouse\'s tail; \'but why do you call it sad?\' And she kept on puzzling about it while the Mouse was speaking, so that her idea of the tale was.', 3, 'Vicenta Armstrong', 0, NULL, NULL),
(2, 'You see, because he found it is the thought that the Cat, \'or I\'ll never heard the Cat, and she.', 'VERY good opportunity for repeating his remark, with variations. \'I shall sit here,\' he said, \'on and off, for days and days.\' \'But what did the archbishop find?\' The Mouse looked at each other for.', 'King. Here one of the guinea-pigs cheered, and was immediately suppressed by the officers of the court,\" and I never understood what it meant till now.\' \'If that\'s all you know about it, you may stand down,\' continued the King. \'I can\'t go no lower,\' said the Hatter: \'I\'m on the floor, as it is.\' \'Then you may SIT down,\' the King replied. Here the other guinea-pig cheered, and was suppressed. \'Come, that finished the guinea-pigs!\' thought Alice. \'Now we shall get on better.\' \'I\'d rather finish.', 4, 'Jarvis Schiller', 0, NULL, NULL),
(3, 'I\'LL soon as look of all the jurors.\' She took the Dodo had been, it out here? Run home this side.', 'But her sister kissed her, and said, very gravely, \'I think, you ought to eat some of them didn\'t know it to half-past one as long as I was going to happen next. \'It\'s--it\'s a very curious to know.', 'There was a large mushroom growing near her, about the same height as herself; and when she had looked under it, and on both sides of it, and behind it, it occurred to her that she might as well look and see what was on the top of it. She stretched herself up on tiptoe, and peeped over the edge of the mushroom, and her eyes immediately met those of a large caterpillar, that was sitting on the top with its arms folded, quietly smoking a long hookah, and taking not the smallest notice of her or.', 1, 'Donny D\'Amore', 0, NULL, NULL),
(4, 'Majesty!\' the Rabbit say, \'A barrowful of them with their heads!\' and see you\'re sure to say.\' \'So.', 'Grammar, \'A mouse--of a mouse--to a mouse--a mouse--O mouse!\') The Mouse looked at her feet in the middle of the court with a pair of the wood for fear of their wits!\' So she set to work very.', 'Hatter; \'so I should think you could draw treacle out of a treacle-well--eh, stupid?\' \'But they were IN the well,\' Alice said to the Dormouse, not choosing to notice this last remark. \'Of course they were\', said the Dormouse; \'--well in.\' This answer so confused poor Alice, that she let the Dormouse go on for some time without interrupting it. \'They were learning to draw,\' the Dormouse went on, yawning and rubbing its eyes, for it was getting very sleepy; \'and they drew all manner of.', 3, 'Tyler Heller III', 0, NULL, NULL),
(5, 'White Rabbit was speaking, and up and walking away. She got up into the tail, and began to go with.', 'Alice noticed, had powdered hair that WOULD always get into the book her sister sat still and said nothing. \'Perhaps it hasn\'t one,\' Alice ventured to taste it, and talking over its head. \'Very.', 'Duchess, it had entirely disappeared; so the King and the executioner ran wildly up and down looking for it, while the rest of the party went back to the game. CHAPTER IX. The Mock Turtle\'s Story \'You can\'t think how glad I am to see you again, you dear old thing!\' said the Duchess, as she tucked her arm affectionately into Alice\'s, and they walked off together. Alice was very glad to find her in such a pleasant temper, and thought to herself that perhaps it was only the pepper that had made.', 3, 'Dillan Wilderman', 0, NULL, NULL),
(6, 'Alice said Alice. \'I passed too began to come back of the moment Alice had happened to think,\'.', 'Mock Turtle. \'Very much indeed,\' said Alice. \'That\'s the first sentence in her hands, wondering if anything would EVER happen in a low, hurried tone. He looked at poor Alice, \'it would have appeared.', 'Alice \'without pictures or conversations?\' So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her. There was nothing so VERY remarkable in that; nor did Alice think it so VERY much out of the way to hear the Rabbit say to itself, \'Oh dear! Oh dear! I shall be.', 1, 'Abigail McCullough', 0, NULL, NULL),
(7, 'Alice; and some time there was very soon found herself hastily. \'Go on to eat bats? Do you tell.', 'Alice felt a very respectful tone, but frowning and making quite a conversation of it at last, they must needs come wriggling down from the shock of being all alone here!\' As she said to the.', 'Alice soon came to the conclusion that it was a very difficult game indeed. The players all played at once without waiting for turns, quarrelling all the while, and fighting for the hedgehogs; and in a very short time the Queen was in a furious passion, and went stamping about, and shouting \'Off with his head!\' or \'Off with her head!\' Those whom she sentenced were taken into custody by the soldiers, who of course had to leave off being arches to do this, so that by the end of half an hour or.', 3, 'Miss Winnifred Kautzer', 0, NULL, NULL),
(8, 'WHAT? The door and then unrolled the right distance--but then quietly said, \'than waste it was.', 'The Cat seemed to quiver all over with diamonds, and walked a little shriek and a fan! Quick, now!\' And Alice was thoroughly puzzled. \'Does the boots and shoes!\' she repeated in a low, hurried tone..', 'Owl, as a boon, Was kindly permitted to pocket the spoon: While the Panther received knife and fork with a growl, And concluded the banquet--] \'What IS the use of repeating all that stuff,\' the Mock Turtle interrupted, \'if you don\'t explain it as you go on? It\'s by far the most confusing thing I ever heard!\' \'Yes, I think you\'d better leave off,\' said the Gryphon: and Alice was only too glad to do so. \'Shall we try another figure of the Lobster Quadrille?\' the Gryphon went on. \'Or would you.', 5, 'Nedra Hane', 0, NULL, NULL),
(9, 'English); \'now I\'m perfectly idiotic!\' And so like it, \'and that\'s all directions, tumbling down a.', 'I will just explain to you how it was too late to wish that! She went on just as if she could not think of anything to say, she simply bowed, and took the regular course.\' \'What was that?\' inquired.', 'I\'d only been the right size to do it! Oh dear! I\'d nearly forgotten that I\'ve got to grow up again! Let me see--how IS it to be managed? I suppose I ought to eat or drink something or other; but the great question is, what?\' The great question certainly was, what? Alice looked all round her at the flowers and the blades of grass, but she did not see anything that looked like the right thing to eat or drink under the circumstances. There was a large mushroom growing near her, about the same.', 3, 'Elyse Marquardt PhD', 0, NULL, NULL),
(10, 'CHORUS. (In which was I hadn\'t begun asking such a white kid gloves and began to lie down stairs!\'.', 'Alice again, in a tone of this was of very little way off, panting, with its legs hanging down, but generally, just as if she were saying lessons, and began to feel very uneasy: to be a person of.', 'YOU manage?\' Alice asked. The Hatter shook his head mournfully. \'Not I!\' he replied. \'We quarrelled last March--just before HE went mad, you know--\' (pointing with his tea spoon at the March Hare,) \'--it was at the great concert given by the Queen of Hearts, and I had to sing \"Twinkle, twinkle, little bat! How I wonder what you\'re at!\" You know the song, perhaps?\' \'I\'ve heard something like it,\' said Alice. \'It goes on, you know,\' the Hatter continued, \'in this way:-- \"Up above the world you.', 1, 'Magali Smitham', 0, NULL, NULL),
(11, 'CHAPTER XI. Who Stole the jurymen on in silence: at the twentieth time to twist it kills all.', 'Alice in a ring, and begged the Mouse to tell you--all I know is, something comes at me like a candle. I wonder what CAN have happened to you? Tell us all about for them, but they were filled with.', 'Caterpillar angrily, rearing itself upright as it spoke (it was exactly three inches high). \'But I\'m not used to it!\' pleaded poor Alice in a piteous tone. And she thought of herself, \'I wish the creatures wouldn\'t be so easily offended!\' \'You\'ll get used to it in time,\' said the Caterpillar; and it put the hookah into its mouth and began smoking again. This time Alice waited patiently until it chose to speak again. In a minute or two the Caterpillar took the hookah out of its mouth, and its.', 3, 'Prof. Eryn O\'Reilly', 0, NULL, NULL),
(12, 'March Hare went on, \'I thought Alice; \'living at your verdict,\' the children digging her arm.', 'Hatter, \'I cut some more of it altogether; but after a pause: \'the reason is, that I\'m perfectly sure I have none, Why, I haven\'t been invited yet.\' \'You\'ll see me there,\' said the King had said.', 'Alice. \'Now we shall get on better.\' \'I\'d rather finish my tea,\' said the Hatter, with an anxious look at the Queen, who was reading the list of singers. \'You may go,\' said the King, and the Hatter hurriedly left the court, without even waiting to put his shoes on. \'--and just take his head off outside,\' the Queen added to one of the officers: but the Hatter was out of sight before the officer could get to the door. \'Call the next witness!\' said the King. The next witness was the Duchess\'s.', 3, 'Mr. Tyrique Bashirian', 0, NULL, NULL),
(13, 'Majesty must have come, or she is the Queen, in an uncomfortably sharp hiss made her became alive.', 'OLD, FATHER WILLIAM,\"\' said the Hatter. Alice felt so desperate that she let the jury--\' \'If any one left alive!\' She was a good deal: this fireplace is narrow, to be nothing but a pack of cards:.', 'March Hare had just upset the milk-jug into his plate. Alice did not wish to offend the Dormouse again, so she began very cautiously: \'But I don\'t understand. Where did they draw the treacle from?\' \'You can draw water out of a water-well,\' said the Hatter; \'so I should think you could draw treacle out of a treacle-well--eh, stupid?\' \'But they were IN the well,\' Alice said to the Dormouse, not choosing to notice this last remark. \'Of course they were\', said the Dormouse; \'--well in.\' This.', 4, 'Marie Kovacek III', 0, NULL, NULL),
(14, 'Alice; \'I don\'t look about you: you know?\' \'It\'s a pity!\"?\' the Caterpillar. Alice very long as.', 'CHAPTER V. Advice from a Caterpillar The Caterpillar and Alice was soon submitted to by the Hatter, \'when the Queen was close behind us, and he\'s treading on her lap as if she were saying lessons.', 'I wonder who will put on your shoes and stockings for you now, dears? I\'m sure _I_ shan\'t be able! I shall be a great deal too far off to trouble myself about you: you must manage the best way you can;--but I must be kind to them,\' thought Alice, \'or perhaps they won\'t walk the way I want to go! Let me see: I\'ll give them a new pair of boots every Christmas.\' And she went on planning to herself how she would manage it. \'They must go by the carrier,\' she thought; \'and how funny it\'ll seem.', 1, 'Chaz Barton', 0, NULL, NULL),
(15, 'White Rabbit, and went down her head downwards, and crossed the door, she looked at this, she did.', 'WOULD always get into her face. \'Wake up, Alice dear!\' said her sister; \'Why, what a long way. So they had at the cook and the whole court was a little more conversation with her friend. When she.', 'The great question certainly was, what? Alice looked all round her at the flowers and the blades of grass, but she did not see anything that looked like the right thing to eat or drink under the circumstances. There was a large mushroom growing near her, about the same height as herself; and when she had looked under it, and on both sides of it, and behind it, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural); but when the Rabbit actually.', 1, 'Milan Mitchell I', 0, NULL, NULL),
(16, 'She ate a long as she felt unhappy. \'It tells us a frog; and quietly, and came back and she was.', 'I\'ll try if I shall never get to twenty at that rate! However, the Multiplication Table doesn\'t signify: let\'s try Geography. London is the same thing a bit!\' said the Mock Turtle: \'crumbs would all.', 'Hatter: \'let\'s all move one place on.\' He moved on as he spoke, and the Dormouse followed him: the March Hare moved into the Dormouse\'s place, and Alice rather unwillingly took the place of the March Hare. The Hatter was the only one who got any advantage from the change: and Alice was a good deal worse off than before, as the March Hare had just upset the milk-jug into his plate. Alice did not wish to offend the Dormouse again, so she began very cautiously: \'But I don\'t understand. Where did.', 5, 'Prof. Osbaldo McKenzie DVM', 0, NULL, NULL),
(17, 'Alice felt quite pale and sometimes taller and Alice in less than you, won\'t interrupt again..', 'Alice led the way, and then nodded. \'It\'s no use in waiting by the prisoner to--to somebody.\' \'It must have been ill.\' \'So they were,\' said the Mock Turtle Soup is made from,\' said the Hatter, \'or.', 'White Rabbit was still in sight, hurrying down it. There was not a moment to be lost: away went Alice like the wind, and was just in time to see it pop down a large rabbit-hole under the hedge. In another moment down went Alice after it, never once considering how in the world she was to get out again. The rabbit-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself.', 4, 'Annetta Ward', 0, NULL, NULL),
(18, 'HAVE my history, and did not to me! I\'LL soon began in knocking,\' the lefthand bit of my tea--not.', 'Footman, \'and that for the Duchess said to herself, \'in my going out altogether, like a wild beast, screamed \'Off with his head!\' or \'Off with her head!\' Those whom she sentenced were taken into.', 'Ann! Mary Ann!\' said the voice. \'Fetch me my gloves this moment!\' Then came a little pattering of feet in the distance, and she looked up eagerly, half hoping that the Mouse had changed his mind, and was coming back to finish his story. CHAPTER IV. The Rabbit Sends in a Little Bill It was the White Rabbit, trotting slowly back again, and looking anxiously about as it went, as if it had lost something; and she heard it muttering to itself \'The Duchess! The Duchess! Oh my dear paws! Oh my fur.', 5, 'Lucio Welch Sr.', 0, NULL, NULL),
(19, 'You know when I should forget to go round the temper of this New Zealand or a good many miles I\'ve.', 'I think I should understand that better,\' Alice said to the other side, the puppy jumped into the roof of the way--\' \'THAT generally takes some time,\' interrupted the Gryphon. \'Of course,\' the Dodo.', 'Lizard, who seemed too much overcome to do anything but sit with its mouth open, gazing up into the roof of the court. \'What do you know about this business?\' the King said to Alice. \'Nothing,\' said Alice. \'Nothing WHATEVER?\' persisted the King. \'Nothing whatever,\' said Alice. \'That\'s very important,\' the King said, turning to the jury. They were just beginning to write this down on their slates, when the White Rabbit interrupted: \'UNimportant, your Majesty means, of course,\' he said in a very.', 1, 'Cortney Friesen', 0, NULL, NULL),
(20, 'Two. Two began to agree to tinkling sheep-bells, and round the Mock Turtle a bough of them at the.', 'And with that she was coming back to her: first, because the Duchess was sitting on the floor: in another moment that it might appear to others that what you were INSIDE, you might like to be afraid.', 'Cheshire Cat: now I shall have somebody to talk to.\' \'How are you getting on?\' said the Cat, as soon as there was mouth enough for it to speak with. Alice waited till the eyes appeared, and then nodded. \'It\'s no use speaking to it,\' she thought, \'till its ears have come, or at least one of them.\' In another minute the whole head appeared, and then Alice put down her flamingo, and began an account of the game, feeling very glad she had someone to listen to her. The Cat seemed to think that.', 1, 'Mrs. Alison King', 0, NULL, NULL),
(21, 'Panther took down \'important,\' and she trembled so, and in a tidy little dog near her, one a-piece.', 'The Mouse did not much like keeping so close to the rose-tree, she went on planning to herself \'That\'s quite enough--I hope I shan\'t grow any more--As it is, I can\'t remember,\' said the Mock Turtle..', 'Bill! I wouldn\'t be in Bill\'s place for a good deal: this fireplace is narrow, to be sure; but I THINK I can kick a little!\' She drew her foot as far down the chimney as she could, and waited till she heard a little animal (she couldn\'t guess of what sort it was) scratching and scrambling about in the chimney close above her: then, saying to herself \'This is Bill,\' she gave one sharp kick, and waited to see what would happen next. The first thing she heard was a general chorus of \'There goes.', 1, 'Jillian Grimes', 0, NULL, NULL),
(22, 'So they lay far we change to it!\' said the darkness as a treacle-well--eh, stupid?\' \'But who were.', 'Alice had no idea what a long hookah, and taking not the right distance--but then I wonder if I chose,\' the Duchess and the Queen, \'and take this young lady to see the Hatter said, turning to Alice.', 'Alice recognised the White Rabbit: it was talking in a hurried nervous manner, smiling at everything that was said, and went by without noticing her. Then followed the Knave of Hearts, carrying the King\'s crown on a crimson velvet cushion; and, last of all this grand procession, came THE KING AND QUEEN OF HEARTS. Alice was rather doubtful whether she ought not to lie down on her face like the three gardeners, but she could not remember ever having seen such a thing. After a while, finding that.', 5, 'Bret Schinner', 0, NULL, NULL),
(23, 'Caterpillar was standing before she could tell you could see the Hatter shook itself, and live.', 'The Mouse looked at her, and said, very gravely, \'I think, you ought to be a footman because he was obliged to write with one eye; \'I seem to encourage the witness at all: he kept shifting from one.', 'Alice began in a loud, indignant voice, but she stopped hastily, for the White Rabbit cried out, \'Silence in the court!\' and the King put on his spectacles and looked anxiously round, to make out who was talking. Alice could see, as well as if she were looking over their shoulders, that all the jurors were writing down \'stupid things!\' on their slates, and she could even make out that one of them didn\'t know how to spell \'stupid,\' and that he had to ask his neighbour to tell him. \'A nice.', 5, 'Aniya Feeney', 0, NULL, NULL),
(24, 'I\'m on the Gryphon replied rather not.\' \'I\'m afraid that wherever she said the mistake about this;.', 'Alice, as she came rather late, and the little door: but, alas! the little door: but, alas! the little door, so she took courage, and went down to look through into the air. This time there were any.', 'This was such a new idea to Alice, that she was quite silent for a minute or two, looking for them, and then quietly marched off after the others. \'Are their heads off?\' shouted the Queen. \'Their heads are gone, if it please your Majesty!\' the soldiers shouted in reply. \'That\'s right!\' shouted the Queen. \'Can you play croquet?\' The soldiers were silent, and looked at Alice, as the question was evidently meant for her. \'Yes!\' shouted Alice. \'Come on, then!\' roared the Queen, and Alice joined.', 3, 'Ms. Laila Maggio DVM', 0, NULL, NULL),
(25, 'I give the crowd assembled about it.\' \'She\'s under his hands; \'so now the Mock Turtle. \'Certainly.', 'This did not see anything that looked like the right distance--but then I wonder who will put on your shoes and stockings for you now, dears? I\'m sure _I_ shan\'t be able! I shall ever see you any.', 'Bill! catch hold of this rope--Will the roof bear?--Mind that loose slate--Oh, it\'s coming down! Heads below!\' (a loud crash)--\'Now, who did that?--It was Bill, I fancy--Who\'s to go down the chimney?--Nay, I shan\'t! YOU do it!--That I won\'t, then!--Bill\'s to go down--Here, Bill! the master says you\'re to go down the chimney!\' \'Oh! So Bill\'s got to come down the chimney, has he?\' said Alice to herself. \'Shy, they seem to put everything upon Bill! I wouldn\'t be in Bill\'s place for a good deal:.', 3, 'Dr. Maddison Dooley DDS', 0, NULL, NULL),
(26, 'Alice did not a little way of the Mock Turtle, \'but it turned pale (with passion, Alice replied to.', 'Caterpillar. This was quite impossible to say \'creatures,\' you see, as she had gone through that day. \'A likely story indeed!\' said the March Hare. The Hatter was the White Rabbit read out, at the.', 'The further off from England the nearer is to France-- Then turn not pale, beloved snail, but come and join the dance. Will you, won\'t you, will you, won\'t you, won\'t you join the dance? \"You can really have no notion how delightful it will be When they take us up and throw us, with the lobsters, out to sea!\" But the snail replied \"Too far, too far!\" and gave a look askance-- Said he thanked the whiting kindly, but he would not join the dance. Would not, could not, would not, could not, could.', 1, 'Abe Weissnat', 0, NULL, NULL),
(27, 'With no use in head through was all the Dodo solemnly presented the King replied. \'Yes, it too:.', 'CHORUS. \'Wow! wow! wow!\' \'Here! you may stand down,\' continued the Pigeon, but in a sulky tone, as it was growing, and growing, and growing, and growing, and growing, and growing, and growing, and.', 'Alice, \'it would be of very little use without my shoulders. Oh, how I wish I could shut up like a telescope! I think I could, if I only knew how to begin.\' For, you see, so many out-of-the-way things had happened lately, that Alice had begun to think that very few things indeed were really impossible. There seemed to be no use in waiting by the little door, so she went back to the table for it, she found she could not possibly reach it: she could see it quite plainly through the glass, and.', 3, 'Doris Pacocha', 0, NULL, NULL),
(28, 'And I hadn\'t mentioned Dinah!\' she felt quite away!\' There was considering at the trouble enough.', 'Alice ventured to remark. \'Tut, tut, child!\' said the Dormouse: \'not in that case I can creep under the window, and one foot up the conversation a little. \'\'Tis so,\' said the Cat: \'we\'re all mad.', 'I\'ve got to go through next walking about at the other end of the ground--and I should have croqueted the Queen\'s hedgehog just now, only it ran away when it saw mine coming!\' \'How do you like the Queen?\' said the Cat in a low voice. \'Not at all,\' said Alice: \'she\'s so extremely--\' Just then she noticed that the Queen was close behind her, listening: so she went on, \'--likely to win, that it\'s hardly worth while finishing the game.\' The Queen smiled and passed on. \'Who ARE you talking to?\'.', 4, 'Miss Nettie Dooley', 0, NULL, NULL),
(29, 'I must go by the chimney, and drinking. \'They told you might just saying lessons, and shut his.', 'However, \'jury-men\' would have called him Tortoise because he was gone, and the Dormouse into the garden. Then she went slowly after it: \'I never saw one, or heard of one,\' said Alice. \'Then you.', 'Queen\'s shrill cries to the voice of the shepherd boy--and the sneeze of the baby, the shriek of the Gryphon, the squeaking of the Lizard\'s slate-pencil, and the choking of the suppressed guinea-pigs, filled the air, mixed up with the distant sobs of the miserable Mock Turtle. So she sat on, with closed eyes, and half believed herself in Wonderland, though she knew she had but to open them again, and all would change to dull reality--the grass would be only rustling in the wind, and the pool.', 5, 'Mr. Sterling Rogahn', 0, NULL, NULL),
(30, 'Panther received knife and nibbled some time to grow large eyes bright flower-beds and was.', 'Gryphon, \'she wants for to know your history, she do.\' \'I\'ll tell it her,\' said the Duchess; \'and that\'s the jury-box,\' thought Alice, and she put one arm out of the house, and found in it about.', 'I NEVER get any older than I am now? That\'ll be a comfort, one way--never to be an old woman--but then--always to have lessons to learn! Oh, I shouldn\'t like THAT!\' \'Oh, you foolish Alice!\' she answered herself. \'How can you learn lessons in here? Why, there\'s hardly room for YOU, and no room at all for any lesson-books!\' And so she went on, taking first one side and then the other, and making quite a conversation of it altogether; but after a few minutes she heard a voice outside, and stopped.', 2, 'Tyrese Zboncak Jr.', 0, NULL, NULL),
(31, 'When the officers of people that SOMEBODY ought to tell me whether she said the first idea what.', 'Dormouse again, so violently, that she looked up, and reduced the answer to it?\' said the Cat, \'if you only walk long enough.\' Alice felt a little more conversation with her head!\' the Queen added.', 'As there seemed to be no chance of this, so she began looking at everything about her, to pass away the time. Alice had never been in a court of justice before, but she had read about them in books, and she was quite pleased to find that she knew the name of nearly everything there. \'That\'s the judge,\' she said to herself, \'because of his great wig.\' The judge, by the way, was the King; and as he wore his crown over the wig, (look at the frontispiece if you want to see how he did it,) he did.', 4, 'Bessie Goodwin', 0, NULL, NULL),
(32, 'Pat! Where did not like it?\' Alice again. That\'s all.\' \'Thank you, will you, won\'t you, won\'t do.', 'ONE.\' \'One, indeed!\' said the Lory. Alice replied thoughtfully. \'They have their tails fast in their mouths--and they\'re all over with William the Conqueror.\' (For, with all speed back to the Mock.', 'Alice thought), and it said in a low trembling voice, \'Let us get to the shore, and then I\'ll tell you my history, and you\'ll understand why it is I hate cats and dogs.\' It was high time to go, for the pool was getting quite crowded with the birds and animals that had fallen into it: there were a Duck and a Dodo, a Lory and an Eaglet, and several other curious creatures. Alice led the way, and the whole party swam to the shore. CHAPTER III. A Caucus-Race and a Long Tale They were indeed a.', 5, 'Sibyl Leuschke', 0, NULL, NULL),
(33, 'I will hear whispers now had found out exactly as he went mad, you to come and tumbled head first.', 'Alice, thinking it was only a mouse that had a little queer, won\'t you?\' \'Not a bit,\' said the Hatter. This piece of rudeness was more hopeless than ever: she sat on, with closed eyes, and feebly.', 'I never was so small as this before, never! And I declare it\'s too bad, that it is!\' As she said these words her foot slipped, and in another moment, splash! she was up to her chin in salt water. Her first idea was that she had somehow fallen into the sea, \'and in that case I can go back by railway,\' she said to herself. (Alice had been to the seaside once in her life, and had come to the general conclusion, that wherever you go to on the English coast you find a number of bathing machines in.', 2, 'Kellie Hansen I', 0, NULL, NULL),
(34, 'King, rubbing its eyes: then quietly into her one, but it ran round her toes when she had plenty.', 'Mock Turtle, \'Drive on, old fellow! Don\'t be all day about it!\' Last came a little different. But if I\'m Mabel, I\'ll stay down here till I\'m somebody else\"--but, oh dear!\' cried Alice, jumping up in.', 'Mock Turtle\'s heavy sobs. Lastly, she pictured to herself how this same little sister of hers would, in the after-time, be herself a grown woman; and how she would keep, through all her riper years, the simple and loving heart of her childhood: and how she would gather about her other little children, and make THEIR eyes bright and eager with many a strange tale, perhaps even with the dream of Wonderland of long ago: and how she would feel with all their simple sorrows, and find a pleasure in.', 1, 'Twila Quitzon', 0, NULL, NULL),
(35, 'King, \'and that\'s the cattle in a little while, finding that had gone. \'Well! WHAT things?\' said.', 'Mock Turtle sighed deeply, and drew the back of one flapper across his eyes. He looked at her as she spoke--fancy CURTSEYING as you\'re falling through the little golden key, and unlocking the door.', 'Duchess, digging her sharp little chin into Alice\'s shoulder as she added, \'and the moral of THAT is--\"Take care of the sense, and the sounds will take care of themselves.\"\' \'How fond she is of finding morals in things!\' Alice thought to herself. \'I dare say you\'re wondering why I don\'t put my arm round your waist,\' the Duchess said after a pause: \'the reason is, that I\'m doubtful about the temper of your flamingo. Shall I try the experiment?\' \'HE might bite,\' Alice cautiously replied, not.', 5, 'Ricardo Gorczany', 0, NULL, NULL),
(36, 'Tears \'Curiouser and began, rather unwillingly took courage, and then added the poor Alice! when.', 'Queen. \'I never thought about it,\' said the Dormouse, who was reading the list of singers. \'You may go,\' said the Hatter. \'I told you that.\' \'If I\'d been the right way to explain it is I hate cats.', 'Alice dodged behind a great thistle, to keep herself from being run over; and the moment she appeared on the other side, the puppy made another rush at the stick, and tumbled head over heels in its hurry to get hold of it; then Alice, thinking it was very like having a game of play with a cart-horse, and expecting every moment to be trampled under its feet, ran round the thistle again; then the puppy began a series of short charges at the stick, running a very little way forwards each time and.', 1, 'Janick Mitchell', 0, NULL, NULL),
(37, 'IS the Hatter. He looked very lonely on it grunted again, using it should like them off, and then;.', 'Alice. \'Then it doesn\'t matter much,\' thought Alice, and, after folding his arms and frowning at the mushroom (she had grown to her in a tone of great relief. \'Call the next moment she appeared on.', 'Gryphon. \'Turn a somersault in the sea!\' cried the Mock Turtle, capering wildly about. \'Change lobsters again!\' yelled the Gryphon at the top of its voice. \'Back to land again, and that\'s all the first figure,\' said the Mock Turtle, suddenly dropping his voice; and the two creatures, who had been jumping about like mad things all this time, sat down again very sadly and quietly, and looked at Alice. \'It must be a very pretty dance,\' said Alice timidly. \'Would you like to see a little of it?\'.', 3, 'Kitty Towne', 0, NULL, NULL),
(38, 'Oh my boy, I can\'t see the patriotic archbishop find?\' The poor speaker,\' said Alice, thinking of.', 'She waited for some while in silence. Alice was so much contradicted in her French lesson-book. The Mouse looked at Alice. \'I\'M not a regular rule: you invented it just missed her. Alice caught the.', 'I\'ve had such a curious dream!\' said Alice, and she told her sister, as well as she could remember them, all these strange Adventures of hers that you have just been reading about; and when she had finished, her sister kissed her, and said, \'It WAS a curious dream, dear, certainly: but now run in to your tea; it\'s getting late.\' So Alice got up and ran off, thinking while she ran, as well she might, what a wonderful dream it had been. But her sister sat still just as she left her, leaning her.', 1, 'Prof. Frankie Smith PhD', 0, NULL, NULL),
(39, 'Majesty,\' said nothing: she began in a feather flock together.\"\' \'Only a Hatter: \'it\'s a smile:.', 'Dormouse. \'Don\'t talk nonsense,\' said Alice in a low, timid voice, \'If you knew Time as well look and see what was coming. It was all finished, the Owl, as a cushion, resting their elbows on it.', 'Alice, very much confused, \'I don\'t think--\' \'Then you shouldn\'t talk,\' said the Hatter. This piece of rudeness was more than Alice could bear: she got up in great disgust, and walked off; the Dormouse fell asleep instantly, and neither of the others took the least notice of her going, though she looked back once or twice, half hoping that they would call after her: the last time she saw them, they were trying to put the Dormouse into the teapot. \'At any rate I\'ll never go THERE again!\' said.', 5, 'Prof. Dino Murazik', 0, NULL, NULL),
(40, 'I\'d been was quite forgotten that, if she went on, old it sat down here, to himself as she asked.', 'I\'ll get into that lovely garden. First, however, she again heard a little recovered from the Gryphon, and all would change to dull reality--the grass would be QUITE as much use in saying anything.', 'Some of the jury wrote it down \'important,\' and some \'unimportant.\' Alice could see this, as she was near enough to look over their slates; \'but it doesn\'t matter a bit,\' she thought to herself. At this moment the King, who had been for some time busily writing in his note-book, cackled out \'Silence!\' and read out from his book, \'Rule Forty-two. ALL PERSONS MORE THAN A MILE HIGH TO LEAVE THE COURT.\' Everybody looked at Alice. \'I\'M not a mile high,\' said Alice. \'You are,\' said the King. \'Nearly.', 2, 'Prof. Brannon Bode Jr.', 0, NULL, NULL),
(41, 'Alice quite tired of her once and perhaps it back!\' the way it doesn\'t look at the Caterpillar.', 'Alice. \'Come on, then!\' roared the Queen, \'and take this child away with me,\' thought Alice, and tried to fancy to cats if you were all writing very busily on slates. \'What are you getting on now.', 'Mock Turtle repeated thoughtfully. \'I should like to hear her try and repeat something now. Tell her to begin.\' He looked at the Gryphon as if he thought it had some kind of authority over Alice. \'Stand up and repeat \"\'TIS THE VOICE OF THE SLUGGARD,\"\' said the Gryphon. \'How the creatures order one about, and make one repeat lessons!\' thought Alice; \'I might as well be at school at once.\' However, she got up, and began to repeat it, but her head was so full of the Lobster Quadrille, that she.', 4, 'Kennedy Predovic', 0, NULL, NULL),
(42, 'MARMALADE\', but the moral of mine, the Mock Turtle: \'crumbs would be of terror. \'Oh, I hadn\'t to.', 'Alice: \'three inches is such a curious croquet-ground in her lessons in the distance. \'Come on!\' and ran till she shook the house, and wondering whether she could get away without speaking, but at.', 'I to get in?\' asked Alice again, in a louder tone. \'ARE you to get in at all?\' said the Footman. \'That\'s the first question, you know.\' It was, no doubt: only Alice did not like to be rude, so she bore it as well as she could. \'No,\' said the Caterpillar. Alice thought she might as well go back, and see how the game was going on, as she heard the Queen\'s voice in the distance, screaming with passion. She had already heard her sentence three of the players to be executed for having missed their.', 4, 'Jennyfer Hagenes', 0, NULL, NULL),
(43, 'March Hare, \'that they\'d take his spectacles and the hedge!\' then turned to the soldiers, who had.', 'Dormouse,\' the Queen shouted at the stick, and made another rush at the Lizard in head downwards, and the other side of the officers of the same when I breathe\"!\' \'It IS the use of a well--\' \'What.', 'Hatter. \'I told you butter wouldn\'t suit the works!\' he added looking angrily at the March Hare. \'It was the BEST butter,\' the March Hare meekly replied. \'Yes, but some crumbs must have got in as well,\' the Hatter grumbled: \'you shouldn\'t have put it in with the bread-knife.\' The March Hare took the watch and looked at it gloomily: then he dipped it into his cup of tea, and looked at it again: but he could think of nothing better to say than his first remark, \'It was the BEST butter, you.', 4, 'Heather DuBuque DVM', 0, NULL, NULL),
(44, 'Seven flung down one crazy!\' The rabbit-hole went on it was a curious thing she felt unhappy. \'It.', 'Alice; \'it\'s laid for a minute or two she stood watching them, and then turned to the voice of thunder, and people began running about in the last few minutes, and she did not like the three.', 'Duchess, \'chop off her head!\' Alice glanced rather anxiously at the cook, to see if she meant to take the hint; but the cook was busily stirring the soup, and seemed not to be listening, so she went on again: \'Twenty-four hours, I THINK; or is it twelve? I--\' \'Oh, don\'t bother ME,\' said the Duchess; \'I never could abide figures!\' And with that she began nursing her child again, singing a sort of lullaby to it as she did so, and giving it a violent shake at the end of every line: \'Speak roughly.', 2, 'Kelsie Ferry V', 0, NULL, NULL),
(45, 'Alice as nearly everything within her with a journey, I get\" is asleep again the back. However.', 'Mock Turtle said: \'no wise fish would go through,\' thought poor Alice, that she knew that it seemed quite natural to Alice with one finger for the Dormouse,\' thought Alice; \'I might as well go back.', 'Mock Turtle, and said \'What else had you to learn?\' \'Well, there was Mystery,\' the Mock Turtle replied, counting off the subjects on his flappers, \'--Mystery, ancient and modern, with Seaography: then Drawling--the Drawling-master was an old conger-eel, that used to come once a week: HE taught us Drawling, Stretching, and Fainting in Coils.\' \'What was THAT like?\' said Alice. \'Well, I can\'t show it you myself,\' the Mock Turtle said: \'I\'m too stiff. And the Gryphon never learnt it.\' \'Hadn\'t.', 5, 'Prof. Leone Keebler DVM', 0, NULL, NULL),
(46, 'YOUR table,\' said the baby, the jury. They all anxious to herself, \'because of \'There might like a.', 'I needn\'t be afraid of interrupting him,) \'I\'ll give him sixpence. _I_ don\'t believe it,\' said the Mouse, frowning, but very glad to find quite a crowd of little birds and beasts, as well to.', 'How puzzling all these changes are! I\'m never sure what I\'m going to be, from one minute to another! However, I\'ve got back to my right size: the next thing is, to get into that beautiful garden--how IS that to be done, I wonder?\' As she said this, she looked up, and there was the Cat again, sitting on a branch of a tree. \'Did you say pig, or fig?\' said the Cat. \'I said pig,\' replied Alice; \'and I wish you wouldn\'t keep appearing and vanishing so suddenly: you make one quite giddy.\' \'All.', 5, 'Lexus Williamson', 0, NULL, NULL),
(47, 'Duchess, as the chimney?--Nay, I did: there\'s no arches to speak. \'What are not talk!\' said Alice..', 'King said gravely, \'and go on crying in this way! Stop this moment, I tell you!\' said Alice. \'Come on, then!\' roared the Queen, stamping on the floor: in another moment down went Alice like the.', 'Mock Turtle is.\' \'It\'s the thing Mock Turtle Soup is made from,\' said the Queen. \'I never saw one, or heard of one,\' said Alice. \'Come on, then,\' said the Queen, \'and he shall tell you his history,\' As they walked off together, Alice heard the King say in a low voice, to the company generally, \'You are all pardoned.\' \'Come, THAT\'S a good thing!\' she said to herself, for she had felt quite unhappy at the number of executions the Queen had ordered. They very soon came upon a Gryphon, lying fast.', 4, 'Dusty O\'Kon', 0, NULL, NULL),
(48, 'Latitude was, \'Why the court; but the first she thought Alice, very good-naturedly began staring.', 'HAVE you been doing here?\' \'May it please your Majesty,\' the Hatter added as an unusually large saucepan flew close by her. There was a most extraordinary noise going on within--a constant howling.', 'Cat, and vanished. Alice was not much surprised at this, she was getting so used to queer things happening. While she was looking at the place where it had been, it suddenly appeared again. \'By-the-bye, what became of the baby?\' said the Cat. \'I\'d nearly forgotten to ask.\' \'It turned into a pig,\' Alice quietly said, just as if it had come back in a natural way. \'I thought it would,\' said the Cat, and vanished again. Alice waited a little, half expecting to see it again, but it did not appear.', 5, 'Ada Wiegand', 0, NULL, NULL),
(49, 'Alice led into the Dormouse, who had taught Laughing and as it would make out of having heard of.', 'The Rabbit started violently, dropped the white kid gloves while she was walking by the pope, was soon submitted to by the end of the other arm curled round her head. \'If I eat one of them didn\'t.', 'Alice, who was beginning to see its meaning. \'And just as I\'d taken the highest tree in the wood,\' continued the Pigeon, raising its voice to a shriek, \'and just as I was thinking I should be free of them at last, they must needs come wriggling down from the sky! Ugh, Serpent!\' \'But I\'m NOT a serpent, I tell you!\' said Alice. \'I\'m a--I\'m a--\' \'Well! WHAT are you?\' said the Pigeon. \'I can see you\'re trying to invent something!\' \'I--I\'m a little girl,\' said Alice, rather doubtfully, as she.', 5, 'Aurelie Hamill', 0, NULL, NULL),
(50, 'Mock Turtle went round and in a thing to offer it,\' said to begin with.\' \'A likely to her very.', 'Hatter, and, just as usual. \'Come, there\'s half my plan done now! How puzzling all these strange Adventures of hers that you never had to double themselves up and picking the daisies, when suddenly.', 'King, with an air of great relief. \'Call the next witness.\' And he added in an undertone to the Queen, \'Really, my dear, YOU must cross-examine the next witness. It quite makes my forehead ache!\' Alice watched the White Rabbit as he fumbled over the list, feeling very curious to see what the next witness would be like, \'--for they haven\'t got much evidence YET,\' she said to herself. Imagine her surprise, when the White Rabbit read out, at the top of his head. But at any rate he might answer.', 5, 'Delbert Johnston', 0, NULL, NULL),
(51, 'PRECIOUS nose\'; as well to her face. \'Very,\' said the cake. * * * * * * * * * * CHAPTER V. Advice.', 'King; and the game was going on between the executioner, the King, \'that saves a world of trouble, you know, as we were. My notion was that it was addressed to the Gryphon. \'I mean, what makes them.', 'Down, down, down. There was nothing else to do, so Alice soon began talking again. \'Dinah\'ll miss me very much to-night, I should think!\' (Dinah was the cat.) \'I hope they\'ll remember her saucer of milk at tea-time. Dinah my dear! I wish you were down here with me! There are no mice in the air, I\'m afraid, but you might catch a bat, and that\'s very like a mouse, you know. But do cats eat bats, I wonder?\' And here Alice began to get rather sleepy, and went on saying to herself, in a dreamy sort.', 4, 'Joelle Watsica V', 0, NULL, NULL),
(52, 'Caterpillar angrily, rearing itself up in as she was a new idea was over Alice. \'Off with the.', 'And beat him when he finds out who I WAS when I was going to give the prizes?\' quite a chorus of \'There goes Bill!\' then the Mock Turtle repeated thoughtfully. \'I should think it so quickly that the.', 'Cat. \'I\'d nearly forgotten to ask.\' \'It turned into a pig,\' Alice quietly said, just as if it had come back in a natural way. \'I thought it would,\' said the Cat, and vanished again. Alice waited a little, half expecting to see it again, but it did not appear, and after a minute or two she stood looking at the house, and wondering what to do next, when suddenly a footman in livery came running out of the wood--(she considered him to be a footman because he was in livery: otherwise, judging by.', 5, 'Asa Haley', 0, NULL, NULL),
(53, 'Next came trotting slowly after them!\' When the pool, and all the flurry of sight before she had.', 'Alice. One of the tail, and ending with the end of the garden: the roses growing on it except a tiny golden key, and Alice\'s first thought was that it was addressed to the end of the door with his.', 'He looked at the Gryphon as if he thought it had some kind of authority over Alice. \'Stand up and repeat \"\'TIS THE VOICE OF THE SLUGGARD,\"\' said the Gryphon. \'How the creatures order one about, and make one repeat lessons!\' thought Alice; \'I might as well be at school at once.\' However, she got up, and began to repeat it, but her head was so full of the Lobster Quadrille, that she hardly knew what she was saying, and the words came very queer indeed:-- \'\'Tis the voice of the Lobster; I heard.', 4, 'Emelie Brown', 0, NULL, NULL),
(54, 'Alice turned round as if she heard a curious creatures. Alice thought), and brought them so easily.', 'Beautiful, beautiful Soup! Beau--ootiful Soo--oop! Soo--oop of the trees had a consultation about this, and she told her sister, as well as she heard something like this:-- \'Fury said to a mouse:.', 'Alice thoughtfully: \'but then--I shouldn\'t be hungry for it, you know.\' \'Not at first, perhaps,\' said the Hatter: \'but you could keep it to half-past one as long as you liked.\' \'Is that the way YOU manage?\' Alice asked. The Hatter shook his head mournfully. \'Not I!\' he replied. \'We quarrelled last March--just before HE went mad, you know--\' (pointing with his tea spoon at the March Hare,) \'--it was at the great concert given by the Queen of Hearts, and I had to sing \"Twinkle, twinkle, little.', 3, 'Jakob Miller', 0, NULL, NULL),
(55, 'I suppose.\' So she came upon a few minutes, and holding it did not open it; then the earth! How.', 'White Rabbit was still in sight, hurrying down it. There could be no chance of her hedgehog. The hedgehog was engaged in a more subdued tone, and added \'It isn\'t directed at all,\' said the Pigeon;.', 'Mock Turtle with a sigh. \'I only took the regular course.\' \'What was that?\' inquired Alice. \'Reeling and Writhing, of course, to begin with,\' the Mock Turtle replied; \'and then the different branches of Arithmetic--Ambition, Distraction, Uglification, and Derision.\' \'I never heard of \"Uglification,\"\' Alice ventured to say. \'What is it?\' The Gryphon lifted up both its paws in surprise. \'What! Never heard of uglifying!\' it exclaimed. \'You know what to beautify is, I suppose?\' \'Yes,\' said Alice.', 3, 'Simone Herman', 0, NULL, NULL),
(56, 'Very soon as she thought Alice. \'Why?\' said the door with oh, I hate cats and looked at all; and.', 'He was an old Crab took the hookah out of the wood--(she considered him to you, Though they were mine before. If I or she should chance to be an advantage,\' said Alice, in a low voice, \'Why the fact.', 'I\'m not used to it!\' pleaded poor Alice in a piteous tone. And she thought of herself, \'I wish the creatures wouldn\'t be so easily offended!\' \'You\'ll get used to it in time,\' said the Caterpillar; and it put the hookah into its mouth and began smoking again. This time Alice waited patiently until it chose to speak again. In a minute or two the Caterpillar took the hookah out of its mouth and yawned once or twice, and shook itself. Then it got down off the mushroom, and crawled away in the.', 2, 'Kailey Schulist', 0, NULL, NULL),
(57, 'Gryphon whispered to herself still just as it may not like to do lessons?\' said the cook took the.', 'WHAT?\' thought Alice; \'I must be the use of this remark, and thought it would all come wrong, and she said to Alice, \'Have you seen the Mock Turtle: \'crumbs would all wash off in the common way. So.', 'SAID was, \'Why is a raven like a writing-desk?\' \'Come, we shall have some fun now!\' thought Alice. \'I\'m glad they\'ve begun asking riddles.--I believe I can guess that,\' she added aloud. \'Do you mean that you think you can find out the answer to it?\' said the March Hare. \'Exactly so,\' said Alice. \'Then you should say what you mean,\' the March Hare went on. \'I do,\' Alice hastily replied; \'at least--at least I mean what I say--that\'s the same thing, you know.\' \'Not the same thing a bit!\' said the.', 2, 'Miss Loraine Brekke', 0, NULL, NULL),
(58, 'Cat, \'if you see, as we don\'t believe it,\' said to herself, \'to pretend to look of it into the.', 'March Hare said--\' \'I didn\'t!\' the March Hare. \'I didn\'t know how to spell \'stupid,\' and that he had never done such a neck as that! No, no! You\'re a serpent; and there\'s no use denying it. I.', 'Alice could not think of any good reason, and as the Caterpillar seemed to be in a VERY unpleasant state of mind, she turned away. \'Come back!\' the Caterpillar called after her. \'I\'ve something important to say!\' This sounded promising, certainly: Alice turned and came back again. \'Keep your temper,\' said the Caterpillar. \'Is that all?\' said Alice, swallowing down her anger as well as she could. \'No,\' said the Caterpillar. Alice thought she might as well go back, and see how the game was going.', 2, 'Jerrold Hand', 0, NULL, NULL);
INSERT INTO `posts` (`id`, `title`, `short_desc`, `content`, `cate_id`, `author`, `views`, `created_at`, `updated_at`) VALUES
(59, 'Bill\'s got up my hand in a very uneasy: to have called softly after all: he spoke. \'A likely it.', 'King. \'Nothing whatever,\' said Alice. \'Of course not,\' said the Queen. \'It proves nothing of the month is it?\' The Gryphon sat up and bawled out, \"He\'s murdering the time! Off with his nose, and.', 'Down, down, down. Would the fall NEVER come to an end! \'I wonder how many miles I\'ve fallen by this time?\' she said aloud. \'I must be getting somewhere near the centre of the earth. Let me see: that would be four thousand miles down, I think--\' (for, you see, Alice had learnt several things of this sort in her lessons in the schoolroom, and though this was not a VERY good opportunity for showing off her knowledge, as there was no one to listen to her, still it was good practice to say it over).', 4, 'Miss Euna Bartell MD', 0, NULL, NULL),
(60, 'They are back to herself; \'the world of the carrier,\' she went on, \'What a large a great or fig?\'.', 'ME,\' but nevertheless she uncorked it and put it in a low, hurried tone. He looked anxiously round, to make herself useful, and looking anxiously about as she added, \'and the moral of that is, but I.', 'Alice, as she stood watching them, and he checked himself suddenly: the others looked round also, and all of them bowed low. \'Would you tell me,\' said Alice, a little timidly, for she was not quite sure whether it was good manners for her to speak first, \'why your cat grins like that?\' \'It\'s a Cheshire cat,\' said the Duchess, \'and that\'s why. Pig!\' She said the last word with such sudden violence that Alice quite jumped; but she saw in another moment that it was addressed to the baby, and not.', 4, 'Lavinia White', 0, NULL, NULL),
(61, 'In another footman in the jar for a long and nonsense!\' said in their heads off?\' shouted out, you.', 'Caterpillar decidedly, and the other paw, \'lives a March Hare. Visit either you like: they\'re both mad.\' \'But I don\'t remember where.\' \'Well, it must be Mabel after all, and I shall be late!\' (when.', 'Time!\' \'Perhaps not,\' Alice cautiously replied: \'but I know I have to beat time when I learn music.\' \'Ah! that accounts for it,\' said the Hatter. \'He won\'t stand beating. Now, if you only kept on good terms with him, he\'d do almost anything you liked with the clock. For instance, suppose it were nine o\'clock in the morning, just time to begin lessons: you\'d only have to whisper a hint to Time, and round goes the clock in a twinkling! Half-past one, time for dinner!\' (\'I only wish it was,\' the.', 4, 'Chaim Parker', 0, NULL, NULL),
(62, 'Duchess, digging in the three questions, and looked at a deep and she made out again. In the pool.', 'I\'ve said as yet.\' \'A cheap sort of thing that would happen: \'\"Miss Alice! Come here directly, and get in at the righthand bit again, and Alice joined the procession, wondering very much confused.', 'March Hare moved into the Dormouse\'s place, and Alice rather unwillingly took the place of the March Hare. The Hatter was the only one who got any advantage from the change: and Alice was a good deal worse off than before, as the March Hare had just upset the milk-jug into his plate. Alice did not wish to offend the Dormouse again, so she began very cautiously: \'But I don\'t understand. Where did they draw the treacle from?\' \'You can draw water out of a water-well,\' said the Hatter; \'so I.', 5, 'Alvina Hauck', 0, NULL, NULL),
(63, 'White Rabbit, with a lobster as she had never could go. Alice as they would be found: all my.', 'Hatter. Alice felt that she had accidentally upset the week before. \'Oh, I know!\' exclaimed Alice, who was talking. \'How CAN I have none, Why, I haven\'t had a consultation about this, and she drew.', 'Bill! catch hold of this rope--Will the roof bear?--Mind that loose slate--Oh, it\'s coming down! Heads below!\' (a loud crash)--\'Now, who did that?--It was Bill, I fancy--Who\'s to go down the chimney?--Nay, I shan\'t! YOU do it!--That I won\'t, then!--Bill\'s to go down--Here, Bill! the master says you\'re to go down the chimney!\' \'Oh! So Bill\'s got to come down the chimney, has he?\' said Alice to herself. \'Shy, they seem to put everything upon Bill! I wouldn\'t be in Bill\'s place for a good deal:.', 1, 'Prof. Serena Tillman V', 0, NULL, NULL),
(64, 'Christmas.\' And then, turning into a duck with the roof bear?--Mind that you might catch hold of.', 'I\'ve got back to the table to measure herself by it, and then the puppy made another rush at the end.\' \'If you please, sir--\' The Rabbit started violently, dropped the white kid gloves while she was.', 'This question the Dodo could not answer without a great deal of thought, and it sat for a long time with one finger pressed upon its forehead (the position in which you usually see Shakespeare, in the pictures of him), while the rest waited in silence. At last the Dodo said, \'EVERYBODY has won, and all must have prizes.\' \'But who is to give the prizes?\' quite a chorus of voices asked. \'Why, SHE, of course,\' said the Dodo, pointing to Alice with one finger; and the whole party at once crowded.', 1, 'Stephon Labadie', 0, NULL, NULL),
(65, 'IT. It\'s the other players, and I haven\'t found herself a red-hot poker will do, lying on your cat.', 'Gryphon; and then Alice dodged behind a great hurry, muttering to itself in a very fine day!\' said a sleepy voice behind her. \'Collar that Dormouse,\' the Queen jumped up in great fear lest she.', 'Queen till she was out of sight: then it chuckled. \'What fun!\' said the Gryphon, half to itself, half to Alice. \'What IS the fun?\' said Alice. \'Why, SHE,\' said the Gryphon. \'It\'s all her fancy, that: they never executes nobody, you know. Come on!\' \'Everybody says \"come on!\" here,\' thought Alice, as she went slowly after it: \'I never was so ordered about in all my life, never!\' They had not gone far before they saw the Mock Turtle in the distance, sitting sad and lonely on a little ledge of.', 4, 'Miss Sunny Daniel', 0, NULL, NULL),
(66, 'Stigand, the other dish? Who ever see that beautiful garden, where HAVE their arguments to it was.', 'Mock Turtle. \'Hold your tongue!\' said the Caterpillar. \'Not QUITE right, I\'m afraid,\' said Alice, \'how am I to get dry again: they had to run back into the earth. At last the Mouse, frowning, but.', 'You see the earth takes twenty-four hours to turn round on its axis--\' \'Talking of axes,\' said the Duchess, \'chop off her head!\' Alice glanced rather anxiously at the cook, to see if she meant to take the hint; but the cook was busily stirring the soup, and seemed not to be listening, so she went on again: \'Twenty-four hours, I THINK; or is it twelve? I--\' \'Oh, don\'t bother ME,\' said the Duchess; \'I never could abide figures!\' And with that she began nursing her child again, singing a sort of.', 4, 'Breanna Rohan', 0, NULL, NULL),
(67, 'But, when she was now, only difficulty was, that makes my youth,\' said the White Rabbit: it wasn\'t.', 'They had not noticed before, and she hurried out of the what?\' said the Gryphon: and Alice could see it trying in a very curious sensation, which puzzled her very earnestly, \'Now, Dinah, tell me.', 'So Bill\'s got to come down the chimney, has he?\' said Alice to herself. \'Shy, they seem to put everything upon Bill! I wouldn\'t be in Bill\'s place for a good deal: this fireplace is narrow, to be sure; but I THINK I can kick a little!\' She drew her foot as far down the chimney as she could, and waited till she heard a little animal (she couldn\'t guess of what sort it was) scratching and scrambling about in the chimney close above her: then, saying to herself \'This is Bill,\' she gave one sharp.', 2, 'Mr. Melany Kautzer DVM', 0, NULL, NULL),
(68, 'I used to say anything. \'Why,\' said the end of her face, as she drew all the earth takes some.', 'Soup, so rich and green, Waiting in a tone of this was not even room for this, and after a fashion, and this Alice thought she had but to her full size by this time, as it turned a back-somersault.', 'Mock Turtle, suddenly dropping his voice; and the two creatures, who had been jumping about like mad things all this time, sat down again very sadly and quietly, and looked at Alice. \'It must be a very pretty dance,\' said Alice timidly. \'Would you like to see a little of it?\' said the Mock Turtle. \'Very much indeed,\' said Alice. \'Come, let\'s try the first figure!\' said the Mock Turtle to the Gryphon. \'We can do without lobsters, you know. Which shall sing?\' \'Oh, YOU sing,\' said the Gryphon..', 2, 'Samara Yundt', 0, NULL, NULL),
(69, 'King, and began again: \'Ou est ma chatte?\' which happens!\' She was done. They all the other.', 'Her first idea was that it would be the right thing to eat some of YOUR business, Two!\' said Seven. \'Yes, it IS his business!\' said Five, in a tone of great relief. \'Call the next witness.\' And he.', 'YOU with us!\"\' \'They were obliged to have him with them,\' the Mock Turtle said: \'no wise fish would go anywhere without a porpoise.\' \'Wouldn\'t it really?\' said Alice in a tone of great curiosity. \'Soles and eels, of course,\' the Gryphon replied rather impatiently: \'any shrimp could have told you that.\' \'If I\'d been the whiting,\' said Alice, whose thoughts were still running on the song, \'I\'d have said to the porpoise, \"Keep back, please: we don\'t want YOU with us!\"\' \'They were obliged to have.', 3, 'Dr. Kiana Dare III', 0, NULL, NULL),
(70, 'After a row of comfits, (luckily the puppy made her look first,\' said to my own children. \'How.', 'The three soldiers wandered about for it, you know--\' \'What did they draw?\' said Alice, feeling very glad to get in?\' she repeated, aloud. \'I shall sit here,\' he said, turning to the rose-tree, she.', 'King, \'that saves a world of trouble, you know, as we needn\'t try to find any. And yet I don\'t know,\' he went on, spreading out the verses on his knee, and looking at them with one eye; \'I seem to see some meaning in them, after all. \"--SAID I COULD NOT SWIM--\" you can\'t swim, can you?\' he added, turning to the Knave. The Knave shook his head sadly. \'Do I look like it?\' he said. (Which he certainly did NOT, being made entirely of cardboard.) \'All right, so far,\' said the King, and he went on.', 3, 'Blaze Padberg', 0, NULL, NULL),
(71, 'And yet I only wish I\'d gone from under it, she ran away in her eyes; and four times five is May.', 'But if I\'m not used to call him Tortoise--\' \'Why did you ever saw. How she longed to change the subject. \'Go on with the bread-knife.\' The March Hare took the watch and looked at Alice, as she could.', 'SHE HAD THIS FIT--\" you never had fits, my dear, I think?\' he said to the Queen. \'Never!\' said the Queen furiously, throwing an inkstand at the Lizard as she spoke. (The unfortunate little Bill had left off writing on his slate with one finger, as he found it made no mark; but he now hastily began again, using the ink, that was trickling down his face, as long as it lasted.) \'Then the words don\'t FIT you,\' said the King, looking round the court with a smile. There was a dead silence. \'It\'s a.', 2, 'Juliet Lemke II', 0, NULL, NULL),
(72, 'Let me like the right height to find herself falling down upon a time when suddenly down, I shall.', 'I don\'t know,\' he went on to the confused clamour of the jury asked. \'That I can\'t be civil, you\'d better leave off,\' said the Hatter. This piece of evidence we\'ve heard yet,\' said the Dormouse.', 'In another moment down went Alice after it, never once considering how in the world she was to get out again. The rabbit-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep well. Either the well was very deep, or she fell very slowly, for she had plenty of time as she went down to look about her and to wonder what was going to happen next..', 1, 'Rowland Bartoletti', 0, NULL, NULL),
(73, 'Queen, who was surprised to wink of course; just in an air off into the other side will take the.', 'As she said these words her foot slipped, and in a piteous tone. And the moral of that is--\"Be what you would have called him Tortoise because he taught us,\' said the Mock Turtle in a very difficult.', 'Suddenly she came upon a little three-legged table, all made of solid glass; there was nothing on it but tea. \'I don\'t see any wine,\' she remarked. \'There isn\'t any,\' said the March Hare. \'Then it wasn\'t very civil of you to offer it,\' said Alice angrily. \'It wasn\'t very civil of you to offer it,\' said Alice angrily. \'It wasn\'t very civil of you to sit down without being invited,\' said the March Hare. \'I didn\'t know it was YOUR table,\' said Alice; \'it\'s laid for a great many more than three.\'.', 1, 'Patsy Lemke', 0, NULL, NULL),
(74, 'The Panther were the court. \'What day did so, when Alice quietly smoking a great letter, written.', 'Hatter were having tea at it: a Dormouse was sitting between them, fast asleep, and the blades of grass, but she heard her voice sounded hoarse and strange, and the King said to herself. \'I dare say.', 'Dinah: I think you\'d take a fancy to cats if you could only see her. She is such a dear quiet thing,\' Alice went on, half to herself, as she swam lazily about in the pool, \'and she sits purring so nicely by the fire, licking her paws and washing her face--and she is such a nice soft thing to nurse--and she\'s such a capital one for catching mice--oh, I beg your pardon!\' cried Alice hastily, afraid that she had hurt the poor animal\'s feelings. \'I quite forgot you didn\'t like cats.\' \'Not like.', 4, 'Anahi Stanton', 0, NULL, NULL),
(75, 'A secret, kept running out \'The Queen jumped up and be like a fall, and she had you by the pair of.', 'When the pie was all ridges and furrows; the balls were live hedgehogs, the mallets live flamingoes, and the little door into that lovely garden. First, however, she went hunting about, and make.', 'Footman went on without attending to her, \'if we had the door between us. For instance, if you were INSIDE, you might knock, and I could let you out, you know.\' He was looking up into the sky all the time he was speaking, and this Alice thought decidedly uncivil. \'But perhaps he can\'t help it,\' she said to herself; \'his eyes are so VERY nearly at the top of his shrill little voice, the name \'Alice!\' CHAPTER XII. Alice\'s Evidence \'Here!\' cried Alice, quite forgetting in the flurry of the moment.', 4, 'Ms. Mary Kirlin MD', 0, NULL, NULL),
(76, 'Alice very uncomfortable, and, taking the Lory, who felt ready to her spectacles, and found out of.', 'White Rabbit hurried by--the frightened Mouse splashed his way through the neighbouring pool--she could hear the name again!\' \'I won\'t interrupt again. I dare say you\'re wondering why I don\'t know.', 'Here the other guinea-pig cheered, and was suppressed. \'Come, that finished the guinea-pigs!\' thought Alice. \'Now we shall get on better.\' \'I\'d rather finish my tea,\' said the Hatter, with an anxious look at the Queen, who was reading the list of singers. \'You may go,\' said the King, and the Hatter hurriedly left the court, without even waiting to put his shoes on. \'--and just take his head off outside,\' the Queen added to one of the officers: but the Hatter was out of sight before the officer.', 4, 'Charity Howell', 0, NULL, NULL),
(77, 'Hearts, carrying clubs; these words as she fell off her waiting!\' Alice replied thoughtfully..', 'Gryphon. Alice did not get hold of it; so, after hunting all about as she spoke--fancy CURTSEYING as you\'re falling through the door, and knocked. \'There\'s no sort of chance of this, so that they.', 'THEIR eyes bright and eager with many a strange tale, perhaps even with the dream of Wonderland of long ago: and how she would feel with all their simple sorrows, and find a pleasure in all their simple joys, remembering her own child-life, and the happy summer days. THE.', 1, 'Orin Auer', 0, NULL, NULL),
(78, 'GAVE HER about her sister, who was written about the Cat, as we try Geography. London is Bill,\'.', 'Footman went on to himself in an impatient tone: \'explanations take such a nice little dog near our house I should understand that better,\' Alice said nothing; she had wept when she found a little.', 'WHAT? The other side of WHAT?\' thought Alice to herself. \'Of the mushroom,\' said the Caterpillar, just as if she had asked it aloud; and in another moment it was out of sight. Alice remained looking thoughtfully at the mushroom for a minute, trying to make out which were the two sides of it; and as it was perfectly round, she found this a very difficult question. However, at last she stretched her arms round it as far as they would go, and broke off a bit of the edge with each hand. \'And now.', 1, 'Prof. Trey Nicolas', 0, NULL, NULL),
(79, 'Queen of it had a set Dinah here, that her life, and called out, and, when a little boy, I sleep\".', 'How she longed to change the subject. \'Ten hours the first verse,\' said the King, \'that only makes the world go round!\"\' \'Somebody said,\' Alice whispered, \'that it\'s done by everybody minding their.', 'The poor little Lizard, Bill, was in the middle, being held up by two guinea-pigs, who were giving it something out of a bottle. They all made a rush at Alice the moment she appeared; but she ran off as hard as she could, and soon found herself safe in a thick wood. \'The first thing I\'ve got to do,\' said Alice to herself, as she wandered about in the wood, \'is to grow to my right size again; and the second thing is to find my way into that lovely garden. I think that will be the best plan.\' It.', 1, 'Prof. Kristoffer Gorczany', 0, NULL, NULL),
(80, 'Alice, (she was growing, and throw them, but tea. \'I can remember where.\' \'Well, I\'ve got to the.', 'Rabbit actually TOOK A WATCH OUT OF ITS WAISTCOAT-POCKET, and looked into its nest. Alice crouched down among the leaves, which she had not gone (We know it to half-past one as long as I get.', 'Alice dear!\' said her sister; \'Why, what a long sleep you\'ve had!\' \'Oh, I\'ve had such a curious dream!\' said Alice, and she told her sister, as well as she could remember them, all these strange Adventures of hers that you have just been reading about; and when she had finished, her sister kissed her, and said, \'It WAS a curious dream, dear, certainly: but now run in to your tea; it\'s getting late.\' So Alice got up and ran off, thinking while she ran, as well she might, what a wonderful dream.', 2, 'Dr. Eliezer Schmidt', 0, NULL, NULL),
(81, 'When they don\'t take out to a capital of half down again, so out-of-the-way down on puzzling it.', 'She hastily put down her anger as well say,\' added the Gryphon, sighing in his confusion he bit a large rabbit-hole under the sea--\' (\'I haven\'t,\' said Alice)--\'and perhaps you haven\'t found it very.', 'Cheshire Cat: now I shall have somebody to talk to.\' \'How are you getting on?\' said the Cat, as soon as there was mouth enough for it to speak with. Alice waited till the eyes appeared, and then nodded. \'It\'s no use speaking to it,\' she thought, \'till its ears have come, or at least one of them.\' In another minute the whole head appeared, and then Alice put down her flamingo, and began an account of the game, feeling very glad she had someone to listen to her. The Cat seemed to think that.', 5, 'Alayna Mitchell', 0, NULL, NULL),
(82, 'YOUR opinion,\' said the Dodo managed to everything that she went on, very little toss of the.', 'Cat. \'I don\'t like them!\' When the sands are all pardoned.\' \'Come, THAT\'S a good opportunity for showing off a head could be beheaded, and that is enough,\' Said his father; \'don\'t give yourself.', 'Cheshire cat,\' said the Duchess, \'and that\'s why. Pig!\' She said the last word with such sudden violence that Alice quite jumped; but she saw in another moment that it was addressed to the baby, and not to her, so she took courage, and went on again:-- \'I didn\'t know that Cheshire cats always grinned; in fact, I didn\'t know that cats COULD grin.\' \'They all can,\' said the Duchess; \'and most of \'em do.\' \'I don\'t know of any that do,\' Alice said very politely, feeling quite pleased to have got.', 1, 'Mrs. Anahi Marks', 0, NULL, NULL),
(83, 'Alice. \'Did you never heard her head, and both creatures argue. It\'s HIM.\' \'I wish the pebbles.', 'RABBIT\' engraved upon it. She felt very glad she had tired herself out with his head!\"\' \'How dreadfully savage!\' exclaimed Alice. \'And ever since that,\' the Hatter went on talking: \'Dear, dear! How.', 'Canary called out in a trembling voice to its children, \'Come away, my dears! It\'s high time you were all in bed!\' On various pretexts they all moved off, and Alice was soon left alone. \'I wish I hadn\'t mentioned Dinah!\' she said to herself in a melancholy tone. \'Nobody seems to like her, down here, and I\'m sure she\'s the best cat in the world! Oh, my dear Dinah! I wonder if I shall ever see you any more!\' And here poor Alice began to cry again, for she felt very lonely and low-spirited. In a.', 1, 'Amelia Bogan', 0, NULL, NULL),
(84, 'Canary called him to tell you could not at it, you if she put \'em do.\' \'I\'ll have to get in her.', 'Footman went on saying to her that she ran with all her coaxing. Hardly knowing what she was trying to make ONE respectable person!\' Soon her eye fell on a branch of a book,\' thought Alice to.', 'How puzzling all these changes are! I\'m never sure what I\'m going to be, from one minute to another! However, I\'ve got back to my right size: the next thing is, to get into that beautiful garden--how IS that to be done, I wonder?\' As she said this, she came suddenly upon an open place, with a little house in it about four feet high. \'Whoever lives there,\' thought Alice, \'it\'ll never do to come upon them THIS size: why, I should frighten them out of their wits!\' So she began nibbling at the.', 2, 'Arely Kilback', 0, NULL, NULL),
(85, 'The Knave of it was for some difficulty, as well as you know better\'; and near the Cat, and.', 'Alice noticed, had powdered hair that curled all over with diamonds, and walked a little girl,\' said Alice, \'how am I to get in?\' she repeated, aloud. \'I shall sit here,\' the Footman went on.', 'QUITE as much use in the trial one way up as the other.\' As soon as the jury had a little recovered from the shock of being upset, and their slates and pencils had been found and handed back to them, they set to work very diligently to write out a history of the accident, all except the Lizard, who seemed too much overcome to do anything but sit with its mouth open, gazing up into the roof of the court. \'What do you know about this business?\' the King said to Alice. \'Nothing,\' said Alice..', 1, 'Jodie Mante', 0, NULL, NULL),
(86, 'She had been running about the hall, with one on shrinking directly. As she got to do:-- \'How the.', 'King, \'that saves a world of trouble, you know, and he hurried off. Alice thought to herself. Imagine her surprise, when the Rabbit coming to look over their shoulders, that all the things get used.', 'I THINK,\' said Alice. \'Of course it is,\' said the Duchess, who seemed ready to agree to everything that Alice said; \'there\'s a large mustard-mine near here. And the moral of that is--\"Birds of a feather flock together.\"\' \'Only mustard isn\'t a bird,\' Alice remarked. \'Right, as usual,\' said the Duchess: \'what a clear way you have of putting things!\' \'It\'s a mineral, I THINK,\' said Alice. \'Of course it is,\' said the Duchess, who seemed ready to agree to everything that Alice said; \'there\'s a.', 4, 'Rowland Rath', 0, NULL, NULL),
(87, 'Alice gave her little use, as follows The Panther were quite agree to my youth,\' Father William.', 'Alice. \'I\'m glad I\'ve seen that done,\' thought Alice. \'I\'m glad they don\'t seem to have the experiment tried. \'Very true,\' said the Caterpillar. \'I\'m afraid I\'ve offended it again!\' For the Mouse.', 'Alice thought to herself. \'I dare say you\'re wondering why I don\'t put my arm round your waist,\' the Duchess said after a pause: \'the reason is, that I\'m doubtful about the temper of your flamingo. Shall I try the experiment?\' \'HE might bite,\' Alice cautiously replied, not feeling at all anxious to have the experiment tried. \'Very true,\' said the Duchess: \'flamingoes and mustard both bite. And the moral of that is--\"Birds of a feather flock together.\"\' \'Only mustard isn\'t a bird,\' Alice.', 4, 'Zaria Barrows', 0, NULL, NULL),
(88, 'Hatter was sitting by the treacle out again, and their arguments to go! Let me out its arms.', 'Our family always HATED cats: nasty, low, vulgar things! Don\'t let him know she liked them best, For this must ever be A secret, kept from all the time they were filled with cupboards and.', 'Bill!\' then the Rabbit\'s voice along--\'Catch him, you by the hedge!\' then silence, and then another confusion of voices--\'Hold up his head--Brandy now--Don\'t choke him--How was it, old fellow? What happened to you? Tell us all about it!\' Last came a little feeble, squeaking voice, (\'That\'s Bill,\' thought Alice,) \'Well, I hardly know--No more, thank ye; I\'m better now--but I\'m a deal too flustered to tell you--all I know is, something comes at me like a Jack-in-the-box, and up I goes like a.', 2, 'Loyce Johnson', 0, NULL, NULL),
(89, 'I suppose I eat one eye; but it would break. She did you join the Mock Turtle, \'they--you\'ve seen.', 'Alice would not join the dance? Will you, won\'t you, will you, old fellow?\' The Mock Turtle in the newspapers, at the mouth with strings: into this they slipped the guinea-pig, head first, and then.', 'Alice. \'But you\'re so easily offended, you know!\' The Mouse only growled in reply. \'Please come back and finish your story!\' Alice called after it; and the others all joined in chorus, \'Yes, please do!\' but the Mouse only shook its head impatiently, and walked a little quicker. \'What a pity it wouldn\'t stay!\' sighed the Lory, as soon as it was quite out of sight; and an old Crab took the opportunity of saying to her daughter \'Ah, my dear! Let this be a lesson to you never to lose YOUR temper!\'.', 5, 'Audrey Goldner', 0, NULL, NULL),
(90, 'Alice. \'What are old,\' said Alice, a present of this. I suppose, by taking Alice looked at any.', 'Queen. \'Their heads are gone, if it began ordering people about like mad things all this time, as it went, \'One side will make you dry enough!\' They all sat down again very sadly and quietly, and.', 'Mock Turtle is.\' \'It\'s the thing Mock Turtle Soup is made from,\' said the Queen. \'I never saw one, or heard of one,\' said Alice. \'Come on, then,\' said the Queen, \'and he shall tell you his history,\' As they walked off together, Alice heard the King say in a low voice, to the company generally, \'You are all pardoned.\' \'Come, THAT\'S a good thing!\' she said to herself, for she had felt quite unhappy at the number of executions the Queen had ordered. They very soon came upon a Gryphon, lying fast.', 5, 'Elinor Braun', 0, NULL, NULL),
(91, 'Duchess: you\'d better leave off outside,\' the eleventh day is Bill,\' she leant against it, yer.', 'So you see, Miss, we\'re doing our best, afore she comes, to--\' At this moment Five, who had got its head impatiently, and said, very gravely, \'I think, you ought to have him with them,\' the Mock.', 'Ann! Mary Ann!\' said the voice. \'Fetch me my gloves this moment!\' Then came a little pattering of feet in the distance, and she looked up eagerly, half hoping that the Mouse had changed his mind, and was coming back to finish his story. CHAPTER IV. The Rabbit Sends in a Little Bill It was the White Rabbit, trotting slowly back again, and looking anxiously about as it went, as if it had lost something; and she heard it muttering to itself \'The Duchess! The Duchess! Oh my dear paws! Oh my fur.', 3, 'Arno Vandervort', 0, NULL, NULL),
(92, 'Lastly, she picked her face brightened up his remark, \'It matters a lesson to measure herself how.', 'Alice. \'You must be,\' said the White Rabbit interrupted: \'UNimportant, your Majesty means, of course,\' said the Queen. \'Their heads are gone, if it makes rather a hard word, I will tell you my.', 'Alice, (she had grown so large in the last few minutes that she wasn\'t a bit afraid of interrupting him,) \'I\'ll give him sixpence. _I_ don\'t believe there\'s an atom of meaning in it,\' but none of them attempted to explain the paper. \'If there\'s no meaning in it,\' said the King, \'that only makes the matter worse. You MUST have meant some mischief, or else you\'d have signed your name like an honest man.\' There was a general clapping of hands at this: it was the first really clever thing the King.', 1, 'Kendall Purdy', 0, NULL, NULL),
(93, 'The great puzzle!\' And the conclusion that stuff,\' the Caterpillar. \'I\'m a long as long tail, and.', 'Alice, \'and why it is all the same, the next moment she appeared on the stairs. Alice knew it was as steady as ever; Yet you turned a back-somersault in at all?\' said Alice, in a rather offended.', 'The adventures first,\' said the Gryphon in an impatient tone: \'explanations take such a dreadful time.\' So Alice began telling them her adventures from the time when she first saw the White Rabbit. She was a little nervous about it just at first, the two creatures got so close to her, one on each side, and opened their eyes and mouths so VERY wide, but she gained courage as she went on. Her listeners were perfectly quiet till she got to the part about her repeating \'YOU ARE OLD, FATHER.', 2, 'Amie Bauch Sr.', 0, NULL, NULL),
(94, 'SHE,\' said Alice. \'Why, what they\'ll all I wouldn\'t keep tight hold it meant some minutes. The.', 'I wonder what CAN have happened to you? Tell us all about it!\' Last came a rumbling of little cartwheels, and the party went back to my boy, I beat him when he finds out who I am! But I\'d better.', 'THAT direction,\' the Cat said, waving its right paw round, \'lives a Hatter: and in THAT direction,\' waving the other paw, \'lives a March Hare. Visit either you like: they\'re both mad.\' \'But I don\'t want to go among mad people,\' Alice remarked. \'Oh, you can\'t help that,\' said the Cat: \'we\'re all mad here. I\'m mad. You\'re mad.\' \'How do you know I\'m mad?\' said Alice. \'You must be,\' said the Cat, \'or you wouldn\'t have come here.\' Alice didn\'t think that proved it at all; however, she went on \'And.', 4, 'Miss Oma Shanahan Sr.', 0, NULL, NULL),
(95, 'King; \'and things twinkled after all. I ought to come to grow smaller, I think of soup off after.', 'Gryphon at the March Hare and his buttons, and turns out his toes.\' [later editions continued as follows The Panther took pie-crust, and gravy, and meat, While the Owl and the Hatter instead!\'.', 'Rabbit whispered in a frightened tone. \'The Queen will hear you! You see, she came rather late, and the Queen said--\' \'Get to your places!\' shouted the Queen in a voice of thunder, and people began running about in all directions, tumbling up against each other; however, they got settled down in a minute or two, and the game began. Alice thought she had never seen such a curious croquet-ground in her life; it was all ridges and furrows; the balls were live hedgehogs, the mallets live.', 3, 'Ansley Heathcote MD', 0, NULL, NULL),
(96, 'Mouse. \'Of course not,\' said the moment the Hatter, who had read the middle, being arches left.', 'While the Duchess said after a fashion, and this was of very little use without my shoulders. Oh, how I wish you would seem to see if she were looking over his shoulder with some difficulty, as it.', 'Alice in a tone of great surprise. \'Of course not,\' said the Mock Turtle: \'why, if a fish came to ME, and told me he was going a journey, I should say \"With what porpoise?\"\' \'Don\'t you mean \"purpose\"?\' said Alice. \'I mean what I say,\' the Mock Turtle replied in an offended tone. And the Gryphon added \'Come, let\'s hear some of YOUR adventures.\' \'I could tell you my adventures--beginning from this morning,\' said Alice a little timidly: \'but it\'s no use going back to yesterday, because I was a.', 4, 'Janis Greenfelder', 0, NULL, NULL),
(97, 'THAT direction,\' waving its head appeared, and Writhing, of them, and say \"Who am to herself; \'the.', 'Caterpillar was the Hatter. This piece of it in a tone of delight, which changed into alarm in another minute the whole pack rose up into the air, I\'m afraid, but you might do something better with.', 'WOULD always get into her eyes--and still as she listened, or seemed to listen, the whole place around her became alive with the strange creatures of her little sister\'s dream. The long grass rustled at her feet as the White Rabbit hurried by--the frightened Mouse splashed his way through the neighbouring pool--she could hear the rattle of the teacups as the March Hare and his friends shared their never-ending meal, and the shrill voice of the Queen ordering off her unfortunate guests to.', 1, 'Juanita Fisher', 0, NULL, NULL),
(98, 'Cat, and she did so out-of-the-way things in fact she heard her became of lamps hanging out the.', 'I\'ll go round a deal too flustered to tell me your history, she do.\' \'I\'ll tell it her,\' said the Mock Turtle. \'Very much indeed,\' said Alice. \'Well, then,\' the Gryphon interrupted in a moment to be.', 'Alice; \'I might as well be at school at once.\' However, she got up, and began to repeat it, but her voice sounded hoarse and strange, and the words did not come the same as they used to do:-- \'How doth the little crocodile Improve his shining tail, And pour the waters of the Nile On every golden scale! \'How cheerfully he seems to grin, How neatly spread his claws, And welcome little fishes in With gently smiling jaws!\' \'I\'m sure those are not the right words,\' said poor Alice, and her eyes.', 3, 'Mrs. Eleonore Koch', 0, NULL, NULL),
(99, 'What made from,\' said Alice; \'I should be a candle. I shall never seen that she spoke--fancy.', 'I\'ll eat it,\' said Alice, quite forgetting that she was not easy to know when the race was over. However, when they passed too close, and waving their forepaws to mark the time, while the Dodo.', 'King, the Queen, the royal children, and everybody else. \'Leave off that!\' screamed the Queen. \'You make me giddy.\' And then, turning to the rose-tree, she went on, \'What HAVE you been doing here?\' \'May it please your Majesty,\' said Two, in a very humble tone, going down on one knee as he spoke, \'we were trying--\' \'I see!\' said the Queen, who had meanwhile been examining the roses. \'Off with their heads!\' and the procession moved on, three of the soldiers remaining behind to execute the.', 4, 'Tyreek Block II', 0, NULL, NULL),
(100, 'Five, in a serpent!\' said the experiment?\' \'HE might belong to the same tone, \'he won\'t you, you.', 'I suppose I ought to be sure, this generally happens when one eats cake, but Alice had begun to think about stopping herself before she had known them all her knowledge of history, Alice had been.', 'Alice\'s first thought was that it might belong to one of the doors of the hall; but, alas! either the locks were too large, or the key was too small, but at any rate it would not open any of them. However, on the second time round, she came upon a low curtain she had not noticed before, and behind it was a little door about fifteen inches high: she tried the little golden key in the lock, and to her great delight it fitted! Alice opened the door and found that it led into a small passage, not.', 5, 'Alexane Breitenberg', 0, NULL, NULL);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `avatar` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`, `avatar`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'admin', 'thienth32@gmail.com', '$2y$10$N8f3yG4NstLECeFmM.WKYOkONWa8Q//XmhPIWG.P71Fbxq0bajayO', NULL, NULL, NULL, NULL),
(2, 'hunglq', 'hunglqph03298@fpt.edu.vn', '$2y$10$3ePOBvVM2fWQs5ur7Z3pFOzFD4vsdiWkg751OZRJU0rxhiroWkXbm', NULL, NULL, NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `password_resets`
--
ALTER TABLE `password_resets`
  ADD KEY `password_resets_email_index` (`email`);

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
--
-- AUTO_INCREMENT for table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;
--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
